=== HoldemPokerTools/RangeAssistant/packages/web/src/ranges/range.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Range",
  "type": "object",
  "properties": {
    "_id": {
      "type": "string",
      "maxLength": 32,
      "minLength": 16
    },
    "title": {
      "type": "string",
      "maxLength": 32,
      "minLength": 1
    },
    "author": {
      "type": "string",
      "maxLength": 24,
      "minLength": 1
    },
    "actions": {
      "$id": "actions",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1,
            "maxLength": 16
          },
          "color": {
            "type": "string",
            "pattern": "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"
          }
        },
        "required": [
          "name",
          "color"
        ]
      },
      "minItems": 2,
      "maxItems": 6,
      "uniqueItems": true
    },
    "combos": {
      "$id": "combos",
      "patternProperties": {
        "^([AKQJT2-9]{2})([os?])?$": {
          "type": "array",
          "items": {
            "type": "number"
          },
          "minItems": 1
        }
      },
      "additionalProperties": false,
      "maxProperties": 169,
      "minProperties": 1
    }
  },
  "required": [
    "_id",
    "title",
    "actions",
    "combos"
  ]
}

=== HoldemPokerTools/RangeAssistant/packages/web/src/examples/push_fold/FR/UTG/ante10/20bb.json
{
  "title": "FR UTG Push/Fold 20BB 10% Ante",
  "author": "Hold'em Tools",
  "combos": {"AA":[0,1],"AKs":[0,1],"AQs":[0,1],"AJs":[0,1],"ATs":[0,1],"AKo":[0,1],"AQo":[0,1],"KK":[0,1],"QQ":[0,1],"JJ":[0,1],"TT":[0,1],"A5s":[0,1],"A4s":[0,1],"KQs":[0,1],"KJs":[0,1],"QJs":[0,1]},
  "actions": [
    {
      "name": "Fold",
      "color": "#d3d3d3"
    },
    {
      "name": "Push",
      "color": "#7ec78e"
    }
  ],
  "_id": "ASR2VHHn1zqiOXpmoVOS4"
}

=== HoldemPokerTools/RangeAssistant/packages/web/src/examples/push_fold/FR/SB/ante10/10bb.json
{
  "title": "FR SB Push/Fold 10BB 10% Ante",
  "author": "Hold'em Tools",
  "combos": {"22":[0,1],"33":[0,1],"44":[0,1],"55":[0,1],"66":[0,1],"77":[0,1],"88":[0,1],"99":[0,1],"AA":[0,1],"AKs":[0,1],"AQs":[0,1],"AJs":[0,1],"ATs":[0,1],"AKo":[0,1],"AQo":[0,1],"KK":[0,1],"QQ":[0,1],"JJ":[0,1],"TT":[0,1],"KQs":[0,1],"KJs":[0,1],"QJs":[0,1],"KTs":[0,1],"QTs":[0,1],"JTs":[0,1],"A9s":[0,1],"K9s":[0,1],"AJo":[0,1],"KQo":[0,1],"A8s":[0,1],"A7s":[0,1],"A6s":[0,1],"A5s":[0,1],"A4s":[0,1],"Q9s":[0,1],"J9s":[0,1],"T9s":[0,1],"ATo":[0,1],"A3s":[0,1],"A2s":[0,1],"K8s":[0,1],"K7s":[0,1],"98s":[0,1],"A9o":[0,1],"A8o":[0,1],"A7o":[0,1],"A5o":[0,1],"KJo":[0,1],"KTo":[0,1],"QJo":[0,1],"K6s":[0,1],"K5s":[0,1],"Q8s":[0,1],"J8s":[0,1],"T8s":[0,1],"A6o":[0,1],"A4o":[0,1],"QTo":[0,1],"JTo":[0,1],"A3o":[0,1],"A2o":[0,1],"K4s":[0,1],"87s":[0,1],"K9o":[0,1],"K3s":[0,1],"K2s":[0,1],"Q7s":[0,1],"Q6s":[0,1],"J7s":[0,1],"97s":[0,1],"K8o":[0,1],"K7o":[0,1],"Q9o":[0,1],"Q5s":[0,1],"Q4s":[0,1],"T7s":[0,1],"76s":[0,1],"K6o":[0,1],"K5o":[0,1],"J9o":[0,1],"T9o":[0,1],"K4o":[0,1],"K3o":[0,1],"K2o":[0,1],"Q8o":[0,1],"Q7o":[0,1],"Q6o":[0,1],"J8o":[0,1],"T8o":[0,1],"98o":[0,1],"86s":[0,1],"96s":[0,1],"T6s":[0,1],"J6s":[0,1],"J5s":[0,1],"J4s":[0,1],"Q3s":[0,1],"Q2s":[0,1],"Q5o":[0,1],"Q4o":[0,1],"Q3o":[0,1],"Q2o":[0,1],"J5o":[0,1],"J6o":[0,1],"J7o":[0,1],"T7o":[0,1],"97o":[0,1],"96o":[0,1],"87o":[0,1],"86o":[0,1],"76o":[0,1],"J2s":[0,1],"93s":[0,1],"T2s":[0,1],"T3s":[0,1],"J3s":[0,1],"T4s":[0,1],"T5s":[0,1],"95s":[0,1],"94s":[0,1],"85s":[0,1],"84s":[0,1],"75s":[0,1],"74s":[0,1],"63s":[0,1],"64s":[0,1],"65s":[0,1],"65o":[0,1],"54s":[0,1],"53s":[0,1],"43s":[0,1]},
  "actions": [
    {
      "name": "Fold",
      "color": "#d3d3d3"
    },
    {
      "name": "Push",
      "color": "#7ec78e"
    }
  ],
  "_id": "CEXsrQss5OGFfKsFuuua2"
}

=== HoldemPokerTools/RangeAssistant/packages/web/src/examples/MTT/RFI/FR/CO/30bb.json
{
  "_id": "GDd2WpgGyJVyEat2fASqX",
  "actions": [
    {
      "name": "Fold",
      "color": "#d3d3d3"
    },
    {
        "name": "Raise/Call/Jam vs 3 Bet",
        "color": "#06ce0c"
    },
    {
        "name": "Call vs 3 Bet",
        "color": "#d9e90e"
    },
    {
        "name": "Fold vs 3 Bet",
        "color": "#fd6363"
    },
    {
        "name": "Call 3 Bet vs BTN",
        "color": "#1b9af7"
    },
    {
        "name": "4 Bet vs 3 Bet",
        "color": "#bb63fd"
    }
  ],
  "author": "Hold'em Poker Tools",
  "combos": {"33":[0,0,0,1,0,0],"44":[0,0,1,0,0,0],"55":[0,0,1,0,0,0],"66":[0,1,0,0,0,0],"77":[0,1,0,0,0,0],"88":[0,1,0,0,0,0],"99":[0,1,0,0,0,0],"AA":[0,1,0,0,0,0],"KK":[0,1,0,0,0,0],"QQ":[0,1,0,0,0,0],"JJ":[0,1,0,0,0,0],"TT":[0,1,0,0,0,0],"AKs":[0,1,0,0,0,0],"AQs":[0,1,0,0,0,0],"AKo":[0,1,0,0,0,0],"AQo":[0,1,0,0,0,0],"AJs":[0,1,0,0,0,0],"ATs":[0,0,1,0,0,0],"KQs":[0,1,0,0,0,0],"KJs":[0,0,1,0,0,0],"KTs":[0,0,1,0,0,0],"QJs":[0,0,1,0,0,0],"A5s":[0,0,1,0,0,1],"A4s":[0,0,1,0,0,1],"A7s":[0,0,1,0,0,0],"A6s":[0,0,1,0,0,0],"ATo":[0,0,1,0,0,0],"KJo":[0,0,1,0,0,0],"K8s":[0,0,1,0,0,0],"Q9s":[0,0,1,0,0,0],"QTs":[0,0,1,0,0,0],"JTs":[0,0,1,0,0,0],"A9s":[0,0,1,0,0,0],"A8s":[0,0,1,0,0,0],"A2s":[0,0,0,0,1,0],"K9s":[0,0,1,0,0,0],"K7s":[0,0,0,0,1,0],"T8s":[0,0,0,1,0,0],"T9s":[0,0,1,0,0,0],"KTo":[0,0,0,1,0,0],"QJo":[0,0,0,1,0,0],"AJo":[0,1,0,0,0,0],"K6s":[0,0,0,0,1,0],"K5s":[0,0,0,0,1,0],"97s":[0,0,0,1,0,0],"A9o":[0,0,0,1,0,0],"J8s":[0,0,0,1,0,0],"Q8s":[0,0,0,0,1,0],"Q6s":[0,0,0,1,0,0],"Q7s":[0,0,0,1,0,0],"J7s":[0,0,0,1,0,0],"T7s":[0,0,0,1,0,0],"86s":[0,0,0,1,0,0],"A8o":[0,0,0,1,0,0],"QTo":[0,0,0,1,0,0],"JTo":[0,0,0,1,0,0],"KQo":[0,0,1,0,0,0],"A7o":[0,0,0,1,0,0],"A6o":[0,0,0,1,0,0],"A5o":[0,0,0,1,0,0],"K9o":[0,0,0,1,0,0],"Q9o":[0,0,0,1,0,0],"J9o":[0,0,0,1,0,0],"T9o":[0,0,0,1,0,0],"J9s":[0,0,0,0,1,0],"98s":[0,0,0,0,1,0],"87s":[0,0,0,0,1,0],"76s":[0,0,0,0,1,0],"96s":[0,0,0,1,0,0],"T6s":[0,0,0,1,0,0],"J6s":[0,0,0,1,0,0],"Q5s":[0,0,0,1,0,0],"Q4s":[0,0,0,1,0,0],"K4s":[0,0,0,1,0,0],"K3s":[0,0,0,1,0,0],"K2s":[0,0,0,1,0,0],"A3s":[0,0,1,0,0,0],"75s":[0,0,0,1,0,0],"65s":[0,0,0,1,0,0],"54s":[0,0,0,1,0,0]},
  "title": "RFI FR CO 30BB"
}

=== HoldemPokerTools/RangeAssistant/packages/web/src/ranges/basic.json
{
  "_id": "12345678901234",
  "actions": [
    {
      "color": "#d3d3d3",
      "name": "Fold"
    },
    {
      "color": "#efe819",
      "name": "Call"
    },
    {
      "color": "#06ce0c",
      "name": "Raise 2BB-3BB"
    },
    {
      "color": "#bb63fd",
      "name": "Raise 4BB-6BB"
    }
  ],
  "author": "Hold'em Tools",
  "combos": {
    "55": [75, 0, 25, 0],
    "66": [50, 0, 50, 0],
    "77": [0, 0, 100, 0],
    "88": [0, 0, 100, 0],
    "99": [0, 0, 100, 0],
    "A5s": [25, 0, 75, 0],
    "A9s": [75, 0, 25, 0],
    "AA": [0, 5, 30, 65],
    "AJo": [0, 0, 100, 0],
    "AJs": [0, 0, 70, 30],
    "AKo": [0, 0, 65, 35],
    "AKs": [0, 0, 35, 65],
    "AQo": [0, 0, 90, 10],
    "AQs": [0, 0, 50, 50],
    "ATo": [75, 0, 25, 0],
    "ATs": [0, 0, 100, 0],
    "JJ": [0, 0, 35, 65],
    "JTs": [0, 0, 100, 0],
    "KJs": [0, 0, 100, 0],
    "KK": [0, 5, 30, 65],
    "KQo": [0, 0, 100, 0],
    "KQs": [0, 0, 100, 0],
    "KTs": [50, 0, 50, 0],
    "QJs": [0, 0, 100, 0],
    "QQ": [0, 5, 30, 65],
    "QTs": [50, 0, 50, 0],
    "TT": [0, 0, 50, 60]
  },
  "title": "FR Cash MP RFI"
}

=== HoldemPokerTools/RangeAssistant/packages/web/src/examples/push_fold/FR/UTG2/ante10/20bb.json
{
  "title": "FR UTG2 Push/Fold 20BB 10% Ante",
  "author": "Hold'em Tools",
  "combos": {"55":[0,1],"66":[0,1],"77":[0,1],"88":[0,1],"99":[0,1],"AA":[0,1],"AKs":[0,1],"AQs":[0,1],"AJs":[0,1],"ATs":[0,1],"AKo":[0,1],"AQo":[0,1],"KK":[0,1],"QQ":[0,1],"JJ":[0,1],"TT":[0,1],"KQs":[0,1],"KJs":[0,1],"QJs":[0,1],"KTs":[0,1],"QTs":[0,1],"JTs":[0,1],"A9s":[0,1],"A5s":[0,1],"A4s":[0,1]},
  "actions": [
    {
      "name": "Fold",
      "color": "#d3d3d3"
    },
    {
      "name": "Push",
      "color": "#7ec78e"
    }
  ],
  "_id": "hruIKdwYHujEH5c1PGF54"
}

=== HoldemPokerTools/RangeAssistant/packages/web/src/examples/multiple.json
{
  "_id": "7d28tXbQgsgPD47YhOWiC",
  "actions": [
    {
      "name": "Fold",
      "color": "#d3d3d3",
      "inRange": false
    },
    {
        "name": "Raise/Call/Jam vs 3 Bet",
        "color": "#06ce0c",
        "inRange": true
    },
    {
        "name": "Call vs 3 Bet",
        "color": "#d9e90e",
       "inRange": true
    },
    {
        "name": "Fold vs 3 Bet",
        "color": "#fd6363",
        "inRange": true
    }
  ],
  "author": "Hold'em Poker Tools",
  "combos": {
    "AA": [0, 1, 0, 0],
    "KK": [0, 1, 0, 0],
    "QQ": [0, 1, 0, 0],
    "JJ": [0, 1, 0, 0],
    "TT": [0, 1, 0, 0],
    "99": [0, 1, 0, 0],
    "AKs": [0, 1, 0, 0],
    "AQs": [0, 1, 0, 0],
    "AKo": [0, 1, 0, 0],
    "AQo": [0, 1, 0, 0],
    "AJs": [0, 0, 1, 0],
    "88": [0, 0, 1, 0],
    "77": [0, 0, 1, 0],
    "66": [0, 0, 1, 0],
    "ATs": [0, 0, 1, 0],
    "KQs": [0, 0, 1, 0],
    "KJs": [0, 0, 1, 0],
    "KTs": [0, 0, 1, 0],
    "QJs": [0, 0, 1, 0],
    "A5s": [0, 0, 1, 0],
    "A4s": [0, 0, 1, 0],
    "A3s": [0, 0, 1, 0],
    "A9s": [0, 0, 0, 1],
    "A8s": [0, 0, 0, 1],
    "A7s": [0, 0, 0, 1],
    "A6s": [0, 0, 0, 1],
    "A2s": [0, 0, 0, 1],
    "AJo": [0, 0, 0, 1],
    "ATo": [0, 0, 0, 1],
    "KQo": [0, 0, 0, 1],
    "KJo": [0, 0, 0, 1],
    "K9s": [0, 0, 0, 1],
    "Q9s": [0, 0, 0, 1],
    "QTs": [0, 0, 0, 1],
    "JTs": [0, 0, 0, 1],
    "J9s": [0, 0, 0, 1],
    "T9s": [0, 0, 0, 1]
  },
  "title": "RFI FR UTG 30BB"
}
